name: PlasmaGlobeIOS
options:
  bundleIdPrefix: com.plasmaglobe
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  developmentLanguage: en

targets:
  PlasmaGlobeIOS:
    type: application
    platform: iOS
    sources:
      - PlasmaGlobeIOS
    settings:
      base:
        INFOPLIST_FILE: PlasmaGlobeIOS/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.plasmaglobe.PlasmaGlobeIOS
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: false
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: -Onone
          MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O
          MTL_ENABLE_DEBUG_INFO: "NO"
